name: SimpleCloud-Placeholder
version: 1.2
author: MrManHD
main: app.simplecloud.placeholder.plugin.paper.PaperPlugin

libraries:
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:2.0.20"
  - "org.jetbrains.kotlin:kotlin-reflect:2.0.20"

depend:
  - PlaceholderAPI
  - simplecloud-api