name: simplecloud-placeholder
version: ${version}
author: MrManHD
main: app.simplecloud.placeholder.plugin.paper.PaperPlugin
folia-supported: true

libraries:
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:2.4.10"
  - "org.jetbrains.kotlin:kotlin-reflect:2.4.10"

depend:
  - PlaceholderAPI
  - simplecloud-api