[versions]
kotlin = "2.0.0"
kotlinX = "1.10.1"
shadow = "8.3.3"
simplecloud = "0.1.0-platform.22-dev.1774376168759-1e20f57"
paper = "1.21.11-R0.1-SNAPSHOT"
placeholder = "2.11.6"
minotaur = "2.8.7"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinX = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinX" }
paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

placeholderApi = { module = "me.clip:placeholderapi", version.ref = "placeholder" }

simplecloud = { module = "app.simplecloud.api:api", version.ref = "simplecloud" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }